return {
	{ "rebelot/kanagawa.nvim", lazy = false, priority = 1000 },
	{ "folke/tokyonight.nvim", lazy = false, priority = 1000 },
	{ "ellisonleao/gruvbox.nvim", lazy = false, priority = 1000 },
	{ "akinsho/bufferline.nvim" },
	{ "nvim-telescope/telescope.nvim" },
	{ "nvim-neo-tree/neo-tree.nvim" },
	{ "nvimdev/dashboard-nvim", event = "VimEnter" },
	{ "nvim-lualine/lualine.nvim" },
	{ "rcarriga/nvim-notify" },
	{ "akinsho/toggleterm.nvim" },
	{ "nvim-telescope/telescope-fzy-native.nvim" },
	{ "folke/which-key.nvim", event = "VeryLazy" },
	{ "RaafatTurki/hex.nvim" },
	{ "b0o/incline.nvim" },
}
